apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
configurations:
- configurations/rollout-transform.yaml
resources:
- oss-deployment.yaml
- oss-svc.yaml
configMapGenerator:
- name: oss-configmap
  envs:
  - ./env/db.env
  - ./env/misc.env
  - ./env/service.env
- name: oss-nginx-conf
  files:
  - nginx/conf.d/vhost.conf
  - nginx/conf.d/vhost.grpc.conf
