apiVersion: v1
kind: Service
metadata:
  name: oss
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: grpc-port
    port: 81
    protocol: TCP
    targetPort: 8180
  selector:
    app: oss
  type: ClusterIP
---
# canary svc
apiVersion: v1
kind: Service
metadata:
  name: oss-canary
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: grpc-port
    port: 81
    protocol: TCP
    targetPort: 8180
  selector:
    app: oss
  type: ClusterIP
