apiVersion: v1
kind: Service
metadata:
  name: backing2
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: grpc-port
    port: 81
    protocol: TCP
    targetPort: 8001
  selector:
    app: backing2
  type: ClusterIP
