apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
- backing2-deployment.yaml
- backing2-svc.yaml
configMapGenerator:
- name: backing2-configmap
  envs:
  - ./env/db.env
  - ./env/misc.env
  - ./env/service.env
- name: backing2-nginx-conf
  files:
  - nginx/conf.d/vhost.conf
  - nginx/conf.d/vhost.grpc.conf
