apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namePrefix: dev-
resources:
- ../../base
configMapGenerator:
- name: auth-configmap
  behavior: merge
  envs:
  - ./env/db.env
  - ./env/misc.env