apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#configurations:
#- configurations/rollout-transform.yaml
# namePrefix: dev-
resources:
- ../../base
configMapGenerator:
- name: auth-configmap
  behavior: merge
  envs:
  - ./env/db.env