apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namePrefix: dev-
resources:
- ../../base
configMapGenerator:
- name: auth-configmap
  behavior: merge
  envs:
  - ./env/db.env
- name: auth-nginx-conf
  behavior: replace
  files:
  - nginx/conf.d/vhost.conf
  - nginx/conf.d/vhost.grpc.conf
