apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
configurations:
- configurations/rollout-transform.yaml
resources:
- prometheus-svc.yaml
- prometheus-deployment.yaml
configMapGenerator:
- name: prometheus-conf
  files:
  - conf/prometheus.yaml