apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react
  type: ClusterIP
---
# canary svc
apiVersion: v1
kind: Service
metadata:
  name: react-canary
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react
  type: ClusterIP
