apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: grpc-port
    port: 81
    protocol: TCP
    targetPort: 8001
  selector:
    app: auth
  type: ClusterIP

---
# canary svc
apiVersion: v1
kind: Service
metadata:
  name: auth-canary
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: grpc-port
    port: 81
    protocol: TCP
    targetPort: 8001
  selector:
    app: auth
  type: ClusterIP
