apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
configurations:
- configurations/rollout-transform.yaml
resources:
- auth-deployment.yaml
- auth-svc.yaml
configMapGenerator:
- name: auth-configmap
  envs:
  - ./env/db.env
  - ./env/misc.env
  - ./env/service.env
