apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  tls:
  - hosts:
    - 'app.go-cinch.top'
    secretName: app-ingress-tls
  ingressClassName: nginx
  defaultBackend:
    service:
      name: auth
      port:
        number: 80
  rules:
  - host: 'app.go-cinch.top'
    http:
      paths:
      - path: /api/auth/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth
            port:
              number: 80