apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
  - host: 'vue3.go-cinch.top'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vue3
            port:
              number: 80
      - path: /api/auth/
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 80
  - host: 'react.go-cinch.top'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vue3
            port:
              number: 80
      - path: /api/auth/
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 80
  - host: 'asynqmon.go-cinch.top'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asynqmon
            port:
              number: 80
