apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
secretGenerator:
- name: app-ingress-tls
  files:
  - tls.crt=certs/server.pem
  - tls.key=certs/server.key
  type: kubernetes.io/tls
  namespace: app
- name: grafana-ingress-tls
  files:
  - tls.crt=certs/server.pem
  - tls.key=certs/server.key
  type: kubernetes.io/tls
  namespace: grafana
- name: prometheus-ingress-tls
  files:
  - tls.crt=certs/server.pem
  - tls.key=certs/server.key
  type: kubernetes.io/tls
  namespace: prometheus
- name: jaeger-ingress-tls
  files:
  - tls.crt=certs/server.pem
  - tls.key=certs/server.key
  type: kubernetes.io/tls
  namespace: jaeger
- name: minio-ingress-tls
  files:
  - tls.crt=certs/server.pem
  - tls.key=certs/server.key
  type: kubernetes.io/tls
  namespace: minio
