apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
secretGenerator:
- name: app-ingress-tls
  files:
  - tls.crt=certs/server.pem
  - tls.key=certs/server.key
  type: kubernetes.io/tls