apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue3
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vue3
  template:
    metadata:
      labels:
        app: vue3
    spec:
      containers:
      - image: ghcr.io/go-cinch/pc-vue3:latest
        imagePullPolicy: Always
        name: vue3
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
        ports:
        - name: http-port
          containerPort: 80 # For http
