apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: vue3
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  # rollout strategy
  strategy:
    canary:
      canaryService: vue3-canary
      stableService: vue3
      trafficRouting:
        nginx:
          stableIngress: app-ingress
          # add canary header
          additionalIngressAnnotations:
            canary-by-header: X-Canary
            canary-by-header-value: iwantsit
      steps:
      - setWeight: 5
      - pause: {}
  selector:
    matchLabels:
      app: vue3
  template:
    metadata:
      labels:
        app: vue3
    spec:
      containers:
      - image: ghcr.io/go-cinch/pc-vue3@sha256:bb06e549621efc5e0891b0a9ecd254277234050f4785fc7a1b95549b827e08e6
        imagePullPolicy: Always
        name: vue3
        resources:
          requests:
            cpu: 50m
            memory: 300Mi
        ports:
        - name: http-port
          containerPort: 80 # For http
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/vhost.conf
          subPath: vhost.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: vue3-nginx-conf
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: vhost.conf
            path: vhost.conf
