apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
configurations:
- configurations/rollout-transform.yaml
resources:
- ocr-deployment.yaml
- ocr-svc.yaml
configMapGenerator:
- name: ocr-det-conf
  files:
  - conf/models/det/inference.pdiparams
  - conf/models/det/inference.pdiparams.info
  - conf/models/det/inference.pdmodel
- name: ocr-rec-conf
  files:
  - conf/models/rec/inference.pdiparams
  - conf/models/rec/inference.pdiparams.info
  - conf/models/rec/inference.pdmodel
- name: ocr-app-conf
  files:
  - conf/ocr_system/config.json
  - conf/ocr_system/module.py
  - conf/ocr_system/params.py
