apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
configurations:
- configurations/rollout-transform.yaml
resources:
- ocr-deployment.yaml
- ocr-svc.yaml
- ocr-pvc.yaml
configMapGenerator:
- name: ocr-app-conf
  files:
  - conf/ocr_system/config.json
  - conf/ocr_system/module.py
  - conf/ocr_system/params.py
