apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
configurations:
- configurations/rollout-transform.yaml
resources:
- ocr-deployment.yaml
- ocr-svc.yaml
- ocr-pvc.yaml
- ocr-hpa.yaml
