apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ocr
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: ocr
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50