apiVersion: v1
kind: Service
metadata:
  name: ocr
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ocr
  type: ClusterIP
---
# canary svc
apiVersion: v1
kind: Service
metadata:
  name: ocr-canary
  namespace: app
spec:
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ocr
  type: ClusterIP
