# https://grafana.com/docs/grafana/latest/setup-grafana/installation/kubernetes/
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grafana
  # rollout strategy
  strategy:
    canary:
      canaryService: grafana-canary
      stableService: grafana
      trafficRouting:
        nginx:
          stableIngress: grafana-ingress
          # add canary header
          additionalIngressAnnotations:
            canary-by-header: X-Canary
            canary-by-header-value: iwantsit
      steps:
      - setWeight: 5
      - pause: {}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
        - 0
      initContainers:
      - name: init-pv-permission
        image: busybox:1.36
        command: ["sh", "-c", "chown -R 472:472 /var/lib/grafana"]
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
      containers:
      - name: grafana
        image: grafana/grafana:11.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http-grafana
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 750Mi
        envFrom:
        - configMapRef:
            name: grafana-configmap
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pvc