apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    type: local
spec:
  storageClassName: minio
  capacity:
    storage: 40Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: minio
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi