apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  ports:
  - name: http-minio
    port: 80
    targetPort: http-minio
  selector:
    app: minio
  type: ClusterIP
---
# canary svc
apiVersion: v1
kind: Service
metadata:
  name: minio-canary
  namespace: minio
spec:
  ports:
  - name: http-minio
    port: 80
    targetPort: http-minio
  selector:
    app: minio
  type: ClusterIP
