apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  namespace: minio
spec:
  ports:
  - name: http-minio-ui
    port: 80
    targetPort: http-minio-ui
  - name: http-minio
    port: 81
    targetPort: http-minio
  selector:
    app: minio
  type: ClusterIP
---
# canary svc
apiVersion: v1
kind: Service
metadata:
  name: minio-ui-canary
  namespace: minio
spec:
  ports:
  - name: http-minio-ui
    port: 80
    targetPort: http-minio-ui
  - name: http-minio
    port: 81
    targetPort: http-minio
  selector:
    app: minio
  type: ClusterIP