# https://stackoverflow.com/questions/69594352/access-mysql-single-instance-kubernetes-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.35
        imagePullPolicy: Always
        name: mysql
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - name: tcp-port
          containerPort: 3306 # For tcp
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      - image: ghcr.io/go-cinch/backing2:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 999 # mysql user id is 999
          runAsGroup: 999
          fsGroup: 999
        name: backing2
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_DATA_DATABASE_ENDPOINT
          value: mysql:3306
        - name: SERVICE_DATA_DATABASE_USERNAME
          value: root
        - name: SERVICE_DATA_DATABASE_PASSWORD
          value: root
        - name: SERVICE_DATA_DATABASE_SCHEMA
          value: backing3
        - name: SERVICE_DATA_DATABASE_DRIVER
          value: mysql
        - name: SERVICE_DATA_REDIS_DSN
          value: redis://redis:6379/0
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
        ports:
        - name: http-port
          containerPort: 8080 # For http
        - name: grpc-port
          containerPort: 8180 # For grpc
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}