# https://stackoverflow.com/questions/69594352/access-mysql-single-instance-kubernetes-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.35
        imagePullPolicy: Always
        name: mysql
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - name: tcp-port
          containerPort: 3306 # For tcp
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}